CONFIG_LOG=y
CONFIG_LOG_CMDS=y
# CONFIG_SHELL=y

CONFIG_LED=y
CONFIG_GPIO=y
CONFIG_SPI=y
# CONFIG_SPI_SHELL=y
CONFIG_SENSOR=y
# CONFIG_SENSOR_SHELL=y
# CONFIG_SENSOR_SHELL_STREAM=y

# CONFIG_ICM45686_STREAM=y
CONFIG_ICM45686_TRIGGER_OWN_THREAD=y
