CONFIG_ASSERT=y
CONFIG_LOG=y
CONFIG_LOG_CMDS=y
# CONFIG_SHELL=y

CONFIG_LED=y
CONFIG_GPIO=y
CONFIG_SPI=y
# CONFIG_SPI_SHELL=y
CONFIG_SENSOR=y
# CONFIG_SENSOR_SHELL=y
# CONFIG_SENSOR_SHELL_STREAM=y

# CONFIG_ICM45686_STREAM=y
CONFIG_ICM45686_TRIGGER_OWN_THREAD=y

CONFIG_FPU=y
CONFIG_ZBUS=y

# Increased stack due to settings API usage
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ATT_PREPARE_COUNT=8
CONFIG_BT_DEVICE_NAME="EdgeML"
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_MAX=8
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_TX_COUNT=4
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
