manifest:
  projects:
    - name: zephyr
      revision: feature-add-lp5521-led-driver
      url: https://github.com/croxel/zephyr
      import: true

  self:
    path: zephyr-playground
    west-commands: scripts/west-commands.yml
    userdata:
      patches_dirs:
        - patches
