manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  defaults:
    remote: ncs

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: v3.1.0-preview4
      path: nrf
      import: true

  self:
    path: zephyr-playground
    west-commands: scripts/west-commands.yml
    userdata:
      patches_dirs:
        - patches
