manifest:
  projects:
    - name: zephyr
      revision: main
      url: https://github.com/zephyrproject-rtos/zephyr
      import: true

  self:
    path: zephyr-playground
    west-commands: scripts/west-commands.yml
    userdata:
      patches_dirs:
        - patches
