name: Run Application Build

on: pull_request

jobs:
  build_app:
    runs-on: ubuntu-22.04
    name: Run Application Build on changes (PR)
    steps:
    - name: Update PATH for west
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: zephyr-playground

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: zephyr-playground
        toolchains: arm-zephyr-eabi

    - name: Patch Repositories
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        west patch

    - name: Build Application
      working-directory: zephyr-playground
      shell: bash
      run: |
        west build -b croxel_cx1825 app
